/*
 * WARNING: This file is autogenerated from scripts/gen_stdef.py. If you would
 * like to know if a certain struct is defined or not, add it to the script
 * and run it from the root directory to update this file.
 */

#define SCX_EVENT_STAT_DEFINED 1
