#!/usr/bin/env python3

import sys
from pathlib import Path

warning = \
"""/*
 * WARNING: This file is autogenerated from scripts/gen_stdef.py. If you would
 * like to know if a certain struct is defined or not, add it to the script
 * and run it from the root directory to update this file.
 */

"""

usage = \
"""
usage: gen_stdef.py [vmlinux.h]

Generating a structure definition header from vmlinux.h
"""

stdefs = [
            ("scx_event_stat", "SCX_EVENT_STAT_DEFINED"),
]

def gen_stdef_h(vmlinux_h):
    autogen = Path.cwd() / "scheds" / "include" / "scx" / "stdef.autogen.h"
    with open(vmlinux_h, "r") as fv:
        with open(autogen, "w") as fa:
            # print a warning message to the generated file
            fa.write(warning)
            # read a vmlinux.h line by line
            for line in fv:
                for st_name, def_name in stdefs:
                    st_str = "struct " + st_name + " {"
                    if line.find(st_str) >= 0:
                        fa.write("#define {} 1\n".format(def_name))

def get_vmlinux_h(argv):
    if len(argv) != 2:
        print(usage)
        exit(1)
    return argv[1]

"""
    Helper script for autogenerating a structure definition header from vmlinux.h.
"""
if __name__ == "__main__":
    vmlinux_h = get_vmlinux_h(sys.argv)
    gen_stdef_h(vmlinux_h)

